export interface Database {
  public: {
    Tables: {
      suppliers: {
        Row: {
          id: string;
          name: string;
          contact: string;
          email: string;
          address: string;
          categories: string[];
          rating: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          contact: string;
          email: string;
          address: string;
          categories?: string[];
          rating?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          contact?: string;
          email?: string;
          address?: string;
          categories?: string[];
          rating?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      purchase_orders: {
        Row: {
          id: string;
          supplier_id: string;
          status: 'pending' | 'approved' | 'ordered' | 'received';
          order_date: string;
          expected_delivery: string;
          total_amount: number;
          notes: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          supplier_id: string;
          status?: 'pending' | 'approved' | 'ordered' | 'received';
          order_date?: string;
          expected_delivery: string;
          total_amount?: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          supplier_id?: string;
          status?: 'pending' | 'approved' | 'ordered' | 'received';
          order_date?: string;
          expected_delivery?: string;
          total_amount?: number;
          notes?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      purchase_order_items: {
        Row: {
          id: string;
          purchase_order_id: string;
          item_id: string;
          quantity: number;
          unit_price: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          purchase_order_id: string;
          item_id: string;
          quantity: number;
          unit_price: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          purchase_order_id?: string;
          item_id?: string;
          quantity?: number;
          unit_price?: number;
          created_at?: string;
        };
      };
      inventory_items: {
        Row: {
          id: string;
          name: string;
          category: 'vegetables' | 'meat' | 'dairy' | 'spices' | 'grains' | 'other';
          current_stock: number;
          unit: string;
          min_stock: number;
          max_stock: number;
          cost_per_unit: number;
          supplier: string;
          last_restocked: string;
          expiry_date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          category: 'vegetables' | 'meat' | 'dairy' | 'spices' | 'grains' | 'other';
          current_stock?: number;
          unit: string;
          min_stock?: number;
          max_stock?: number;
          cost_per_unit?: number;
          supplier: string;
          last_restocked?: string;
          expiry_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          category?: 'vegetables' | 'meat' | 'dairy' | 'spices' | 'grains' | 'other';
          current_stock?: number;
          unit?: string;
          min_stock?: number;
          max_stock?: number;
          cost_per_unit?: number;
          supplier?: string;
          last_restocked?: string;
          expiry_date?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      recipes: {
        Row: {
          id: string;
          name: string;
          category: string;
          prep_time: number;
          cook_time: number;
          servings: number;
          ingredients: any;
          instructions: string[];
          image: string | null;
          difficulty: 'easy' | 'medium' | 'hard';
          cuisine: string | null;
          tags: string[];
          nutrition_info: any;
          cost: number;
          allergens: string[];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          category: string;
          prep_time?: number;
          cook_time?: number;
          servings?: number;
          ingredients?: any;
          instructions?: string[];
          image?: string | null;
          difficulty?: 'easy' | 'medium' | 'hard';
          cuisine?: string | null;
          tags?: string[];
          nutrition_info?: any;
          cost?: number;
          allergens?: string[];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          category?: string;
          prep_time?: number;
          cook_time?: number;
          servings?: number;
          ingredients?: any;
          instructions?: string[];
          image?: string | null;
          difficulty?: 'easy' | 'medium' | 'hard';
          cuisine?: string | null;
          tags?: string[];
          nutrition_info?: any;
          cost?: number;
          allergens?: string[];
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          order_number: string | null;
          customer_name: string;
          customer_phone: string;
          customer_email: string | null;
          delivery_address: string;
          items: any;
          status: 'pending' | 'cooking' | 'out_for_delivery' | 'delivered' | 'cancelled';
          order_time: string;
          estimated_delivery: string;
          total_amount: number;
          assigned_staff: string | null;
          priority: 'low' | 'normal' | 'high' | 'urgent';
          special_instructions: string | null;
          payment_method: 'cash' | 'card' | 'online';
          order_source: 'admin' | 'phone' | 'online';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_number?: string | null;
          customer_name: string;
          customer_phone: string;
          customer_email?: string | null;
          delivery_address: string;
          items?: any;
          status?: 'pending' | 'cooking' | 'out_for_delivery' | 'delivered' | 'cancelled';
          order_time?: string;
          estimated_delivery: string;
          total_amount?: number;
          assigned_staff?: string | null;
          priority?: 'low' | 'normal' | 'high' | 'urgent';
          special_instructions?: string | null;
          payment_method?: 'cash' | 'card' | 'online';
          order_source?: 'admin' | 'phone' | 'online';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_number?: string | null;
          customer_name?: string;
          customer_phone?: string;
          customer_email?: string | null;
          delivery_address?: string;
          items?: any;
          status?: 'pending' | 'cooking' | 'out_for_delivery' | 'delivered' | 'cancelled';
          order_time?: string;
          estimated_delivery?: string;
          total_amount?: number;
          assigned_staff?: string | null;
          priority?: 'low' | 'normal' | 'high' | 'urgent';
          special_instructions?: string | null;
          payment_method?: 'cash' | 'card' | 'online';
          order_source?: 'admin' | 'phone' | 'online';
          created_at?: string;
          updated_at?: string;
        };
      };
      customers: {
        Row: {
          id: string;
          name: string;
          phone: string;
          email: string | null;
          addresses: any;
          order_history: any;
          total_orders: number;
          total_spent: number;
          average_order_value: number;
          last_order_date: string | null;
          customer_since: string;
          preferences: any;
          loyalty_points: number;
          status: 'active' | 'inactive' | 'vip';
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          phone: string;
          email?: string | null;
          addresses?: any;
          order_history?: any;
          total_orders?: number;
          total_spent?: number;
          average_order_value?: number;
          last_order_date?: string | null;
          customer_since?: string;
          preferences?: any;
          loyalty_points?: number;
          status?: 'active' | 'inactive' | 'vip';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          phone?: string;
          email?: string | null;
          addresses?: any;
          order_history?: any;
          total_orders?: number;
          total_spent?: number;
          average_order_value?: number;
          last_order_date?: string | null;
          customer_since?: string;
          preferences?: any;
          loyalty_points?: number;
          status?: 'active' | 'inactive' | 'vip';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      staff_members: {
        Row: {
          id: string;
          name: string;
          email: string;
          phone: string;
          role: 'admin' | 'kitchen_staff' | 'inventory_manager' | 'delivery_staff';
          department: string;
          salary: number;
          username: string;
          password_hash: string;
          join_date: string;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          email: string;
          phone: string;
          role: 'admin' | 'kitchen_staff' | 'inventory_manager' | 'delivery_staff';
          department: string;
          salary?: number;
          username: string;
          password_hash: string;
          join_date?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          email?: string;
          phone?: string;
          role?: 'admin' | 'kitchen_staff' | 'inventory_manager' | 'delivery_staff';
          department?: string;
          salary?: number;
          username?: string;
          password_hash?: string;
          join_date?: string;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      stock_movements: {
        Row: {
          id: string;
          inventory_item_id: string;
          movement_type: 'in' | 'out';
          quantity: number;
          reason: string;
          reference_number: string | null;
          unit_cost: number;
          total_cost: number;
          performed_by: string;
          notes: string;
          movement_date: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          inventory_item_id: string;
          movement_type: 'in' | 'out';
          quantity: number;
          reason: string;
          reference_number?: string | null;
          unit_cost?: number;
          total_cost?: number;
          performed_by: string;
          notes?: string;
          movement_date?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          inventory_item_id?: string;
          movement_type?: 'in' | 'out';
          quantity?: number;
          reason?: string;
          reference_number?: string | null;
          unit_cost?: number;
          total_cost?: number;
          performed_by?: string;
          notes?: string;
          movement_date?: string;
          created_at?: string;
        };
      };
      delivery_confirmations: {
        Row: {
          id: string;
          order_id: string;
          delivered_quantity: number;
          ordered_quantity: number;
          delivery_notes: string;
          delivered_by: string;
          delivery_date: string;
          customer_signature: string | null;
          delivery_status: 'completed' | 'partial' | 'failed';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_id: string;
          delivered_quantity: number;
          ordered_quantity: number;
          delivery_notes?: string;
          delivered_by: string;
          delivery_date?: string;
          customer_signature?: string | null;
          delivery_status?: 'completed' | 'partial' | 'failed';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string;
          delivered_quantity?: number;
          ordered_quantity?: number;
          delivery_notes?: string;
          delivered_by?: string;
          delivery_date?: string;
          customer_signature?: string | null;
          delivery_status?: 'completed' | 'partial' | 'failed';
          created_at?: string;
          updated_at?: string;
        };
      };
      products: {
        Row: {
          id: string;
          name: string;
          description: string;
          sku: string;
          category: string;
          unit: string;
          current_stock: number;
          min_stock: number;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string;
          sku: string;
          category: string;
          unit: string;
          current_stock?: number;
          min_stock?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string;
          sku?: string;
          category?: string;
          unit?: string;
          current_stock?: number;
          min_stock?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      purchase_transactions: {
        Row: {
          id: string;
          product_id: string;
          supplier_name: string;
          quantity: number;
          purchase_price: number;
          total_cost: number;
          purchase_date: string;
          invoice_number: string | null;
          notes: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          supplier_name: string;
          quantity: number;
          purchase_price: number;
          total_cost: number;
          purchase_date?: string;
          invoice_number?: string | null;
          notes?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          supplier_name?: string;
          quantity?: number;
          purchase_price?: number;
          total_cost?: number;
          purchase_date?: string;
          invoice_number?: string | null;
          notes?: string;
          created_at?: string;
        };
      };
      sale_transactions: {
        Row: {
          id: string;
          product_id: string;
          customer_name: string;
          customer_phone: string;
          customer_email: string | null;
          quantity: number;
          sale_price: number;
          total_amount: number;
          profit_margin: number;
          sale_date: string;
          payment_method: 'cash' | 'card' | 'online' | 'credit';
          notes: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          product_id: string;
          customer_name: string;
          customer_phone: string;
          customer_email?: string | null;
          quantity: number;
          sale_price: number;
          total_amount?: number;
          profit_margin?: number;
          sale_date?: string;
          payment_method?: 'cash' | 'card' | 'online' | 'credit';
          notes?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          product_id?: string;
          customer_name?: string;
          customer_phone?: string;
          customer_email?: string | null;
          quantity?: number;
          sale_price?: number;
          total_amount?: number;
          profit_margin?: number;
          sale_date?: string;
          payment_method?: 'cash' | 'card' | 'online' | 'credit';
          notes?: string;
          created_at?: string;
        };
      };
    };
  };
}